export const DAPR_BINDING_METADATA = 'DAPR_BINDING_METADATA';
export const DAPR_PUBSUB_METADATA = 'DAPR_PUBSUB_METADATA';
export const DAPR_ACTOR_METADATA = 'DAPR_ACTOR_METADATA';
export const DAPR_ACTOR_STATE_METADATA = 'DAPR_ACTOR_STATE_METADATA';
