apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: resiliency
spec:
  policies:
    retries:
      pubsubRetry:
        policy: constant
        duration: 5s
        maxRetries: 5
  targets:
    components:
      redis-pubsub:
        inbound:
          retry: pubsubRetry
